apiVersion: v1
kind: Service
metadata:
  name: Demo-falcon
  namespace: falcon
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: Demo-falcon
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000